

axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client


# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
# mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize


bind=Super+SHIFT,R,togglegaps
# reload config
bind=SUPER,r,reload_config

# menu and terminal
bind=Super,d,spawn,rofi -show drun

# |------| #
# |-APPS-| #
# |------| #
bind=Super,T,spawn,alacritty
bind=Super,W,spawn,firefox
bind=Super,E,spawn,nemo


# utilities
bind=Super+Shift,S,spawn_shell,grim -g "$(slurp)" - | wl-copy
bind=Super,V,spawn_shell,cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy
bind=Ctrl+Alt,Delete,spawn_shell,~/.config/rofi/power-menu.sh
# bind=Super,V,spawn,cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy
# exit
bind=SUPER,m,quit
bind=Super,q,killclient

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=Super,Left,focusdir,left
bind=Super,Right,focusdir,right
bind=Super,Up,focusdir,up
bind=Super,Down,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=Super,Space,togglefloating,
bind=Super,F,togglemaximizescreen,
bind=SUPER+SHIFT,f,togglefullscreen,
# bind=SUPER+SHIFT,f,togglefakefullscreen,
# bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
# bind=SUPER+SHIFT,I,restore_minimized
# bind=ALT,z,toggle_scratchpad

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# switch layout
bind=SUPER,n,switch_layout

# tag switch
bind=CTRL+SUPER,Left,viewtoleft,0
# bind=CTRL,Left,viewtoleft_have_client,0
bind=CTRL+SUPER,Right,viewtoright,0
# bind=CTRL,Right,viewtoright_have_client,0
bind=CTRL+SHIFT+SUPER,Left,tagtoleft,0
bind=CTRL+SHIFT+SUPER,Right,tagtoright,0

bind=Super,1,view,1,0
bind=Super,2,view,2,0
bind=Super,3,view,3,0
bind=Super,4,view,4,0
bind=Super,5,view,5,0
bind=Super,6,view,6,0
bind=Super,7,view,7,0
bind=Super,8,view,8,0
bind=Super,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=Shift+Super,1,tag,1,0
bind=Shift+Super,2,tag,2,0
bind=Shift+Super,3,tag,3,0
bind=Shift+Super,4,tag,4,0
bind=Shift+Super,5,tag,5,0
bind=Shift+Super,6,tag,6,0
bind=Shift+Super,7,tag,7,0
bind=Shift+Super,8,tag,8,0
bind=Shift+Super,9,tag,9,0

