monitorrule=name:^HDMI-A-1$,width:1920,height:1080,refresh:60,x:0,y:40,scale:1,rr:0,vrr:0
monitorrule=name:^DP-1$,width:2560,height:1440,refresh:180,x:1920,y:0,scale:1.25,rr:0,vrr:0
env=DISPLAY,:2
exec-once=xwayland-satellite :2
allow_tearing=1
